#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user:
    path: /user
    controller: App\Controller\UserController::index

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]
